"""Generator and loader for library-source-map.json.

Maps Maven/npm coordinates to source-repo clone paths. Generated by
src2sink-build from per-repo dependency data; manual edits to
``status`` and ``clone_path`` fields are preserved on regeneration.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from ..repo_utils import _build_component_identity_index

STATUS_PENDING = "pending"
STATUS_CLONED = "cloned"
STATUS_EXCLUDED = "excluded"
STATUS_AMBIGUOUS = "ambiguous"


def load_library_source_map(path: Path) -> dict[str, dict[str, Any]]:
    """Return coord -> entry dict, or {} if the file is missing/invalid."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {m["coordinate"]: m for m in data.get("mappings", []) if "coordinate" in m}


def generate_library_source_map(metabase_root: Path, repo_jsons: list[Path]) -> None:
    """Write/update library-source-map.json from per-repo internal dependency data."""
    map_path = metabase_root / "library-source-map.json"
    existing = load_library_source_map(map_path)

    # Collect all internal deps from per-repo JSONs
    coord_consumers: dict[str, int] = defaultdict(int)
    coord_versions: dict[str, set[str]] = defaultdict(set)

    for jp in repo_jsons:
        try:
            data = json.loads(jp.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        for dep in data.get("dependencies_internal", []):
            gid = dep.get("groupId", "")
            aid = dep.get("artifactId", "")
            ver = dep.get("version", "")
            if not aid:
                continue
            coord = f"{gid}:{aid}" if gid else aid
            coord_consumers[coord] += 1
            if ver:
                coord_versions[coord].add(ver)

    # Build updated mappings, preserving manual overrides
    mappings: list[dict[str, Any]] = []
    for coord, count in sorted(coord_consumers.items(), key=lambda x: -x[1]):
        prev = existing.get(coord, {})
        # Preserve manually-set status and clone_path overrides
        status = prev.get("status", STATUS_PENDING)
        clone_path = prev.get("clone_path") or _infer_clone_path(coord)
        entry: dict[str, Any] = {
            "coordinate": coord,
            "clone_path": clone_path or "",
            "status": status,
            "consumers": count,
        }
        versions = sorted(coord_versions.get(coord, set()))
        if versions:
            entry["versions"] = versions
        if prev.get("notes"):
            entry["notes"] = prev["notes"]
        mappings.append(entry)

    out = {
        "_comment": (
            "Map of Maven/npm coordinates to source-repo clone paths. "
            "Generated by src2sink-build from per-repo dependency data. "
            "Edit 'status' ('pending'|'cloned'|'excluded') and 'clone_path' to "
            "guide curate_internal_libraries.py. Changes are preserved on regeneration."
        ),
        "mappings": mappings,
    }
    map_path.write_text(json.dumps(out, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def _resolve_clone_path(
    coord: str,
    by_coord: dict[tuple[str, str], str],
    by_name: dict[str, list[str]],
    by_full: dict[str, str],
) -> str | None:
    """Resolve a dependency coordinate to a clone path via the identity index."""
    # 1. Exact canonical-coordinate match.
    if coord in by_full:
        return by_full[coord]
    if ":" in coord:
        group, artifact = coord.split(":", 1)
        # 2. group:artifact pair.
        hit = by_coord.get((group, artifact))
        if hit:
            return hit
        # 3. The artifact half may itself be a full name (scoped npm, vendor/pkg).
        if artifact in by_full:
            return by_full[artifact]
        candidates = by_name.get(artifact, [])
        return candidates[0] if len(candidates) == 1 else None
    # No group: try a group-less pair, then a unique bare-name match.
    hit = by_coord.get(("", coord))
    if hit:
        return hit
    candidates = by_name.get(coord, [])
    return candidates[0] if len(candidates) == 1 else None


def _entry_needs_resolution(entry: dict[str, Any]) -> bool:
    """True if a source-map entry is still flagged and worth resolving."""
    if not entry.get("coordinate"):
        return False
    status = entry.get("status")
    if status == STATUS_EXCLUDED:
        return False
    if status == STATUS_CLONED and entry.get("clone_path"):
        return False
    return True


def fix_flagged_mappings(metabase_root: Path, repos_root: Path) -> int:
    """Resolve flagged source-map entries from on-disk project manifests.

    Walks every recognised project-definition file under ``repos_root`` —
    Maven (``pom.xml``), Gradle (``build.gradle``/``settings.gradle`` ±kts),
    npm (``package.json``), Python (``pyproject.toml``/``setup.cfg``), Rust
    (``Cargo.toml``), Go (``go.mod``), PHP (``composer.json``), .NET
    (``*.csproj``/``*.fsproj``/``*.vbproj``) and Ruby (``*.gemspec``) — and
    reads each project's declared identity. For any mapping still flagged
    (status ``pending`` / ``ambiguous``, or missing a ``clone_path``) whose
    coordinate matches a discovered project, sets ``clone_path`` to that repo's
    path (relative to ``repos_root``) and marks the status ``cloned``.
    ``excluded`` and already-resolved ``cloned`` entries are left untouched.

    Matching tries, in order: the exact coordinate string (npm ``@scope/pkg``,
    Composer ``vendor/pkg``, Go module path, bare names), then the
    ``group:artifact`` pair, then a unique bare-name match.

    Returns the number of mappings corrected.
    """
    map_path = metabase_root / "library-source-map.json"
    try:
        data = json.loads(map_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return 0
    mappings = data.get("mappings")
    if not isinstance(mappings, list) or not mappings:
        return 0


    by_coord, by_name, by_full = _build_component_identity_index(repos_root)

    fixed = 0
    for entry in mappings:
        if not isinstance(entry, dict) or not _entry_needs_resolution(entry):
            continue
        clone_path = _resolve_clone_path(entry["coordinate"], by_coord, by_name, by_full)
        if not clone_path:
            continue
        entry["clone_path"] = clone_path
        entry["status"] = STATUS_CLONED
        entry.pop("notes", None)
        fixed += 1

    if fixed:
        map_path.write_text(
            json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8"
        )
    return fixed


def _infer_clone_path(coord: str) -> str | None:
    """Best-effort inference of group/artifact from a Maven coordinate."""
    if ":" not in coord:
        return None
    group, artifact = coord.split(":", 1)
    # Strip common org prefix patterns to get a GitLab group name
    parts = group.split(".")
    # Heuristic: last meaningful segment of the group + artifact name
    group_hint = parts[-1] if len(parts) > 2 else parts[-1]
    return f"{group_hint}/{artifact}"
